repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_validate

    - id: terraform_docs
      args:
      - --hook-config=--output-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
      