name: "Terraform Pipeline CI/CD"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  TERRAFORM_VERSION: 1.10.3
  # PROJECT_NAME: projeto_eks
  # AWS_REGION: us-east-2
  # EKS_VERSION: 1.29
  # TAGS: Env = dev
    

jobs:
  build:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform plan
      id: plan
      run: terraform plan -var-file=terraform.tfvars.example -out=tfplan
  
  trivy-scan:
    needs: build
    name: "Trivy Scan"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: config
        hide-progress: true
        output: trivy.txt
    
    - name: Publish Trivy Output to Summary
      run: |
        if [[ -s trivy.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat trivy.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        fi
      


    # - uses: actions/github-script@v6
    # if: github.event_name == 'pull_request'
    #   env:
    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
    #   with:
    #     script: |
    #         const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
    #         #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
    #         #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
    #         #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

    #         <details><summary>Show Plan</summary>
      
    